/**
 * generate-self-test.ts
 *
 * Generates .github/workflows/self-test.yml and scripts/self-test-manifest.json
 * from declarative scenario definitions in ./scenarios.ts.
 *
 * Usage:  npx tsx scripts/generate-self-test.ts
 */

import { dirname, join } from "path";
import { fileURLToPath } from "url";
import { writeFileSync, mkdirSync } from "fs";
import { SCENARIOS } from "./scenarios.js";
import type { Scenario } from "./scenarios.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const workflowPath = join(__dirname, "..", ".github", "workflows", "self-test.yml");
const realisticWorkflowPath = join(
  __dirname,
  "..",
  ".github",
  "workflows",
  "realistic-test.yml"
);
const manifestPath = join(__dirname, "self-test-manifest.json");
const ARTIFACT_PREFIX = "github-api-usage-monitor";
const SELF_TEST_SCENARIOS = SCENARIOS.filter((s) => s.suite !== "realistic");
const REALISTIC_SCENARIOS = SCENARIOS.filter((s) => s.suite === "realistic");

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Escape a string for use inside a YAML double-quoted scalar.
 * Replaces backslashes and double quotes with their escape sequences.
 */
function yamlEscape(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function scenarioInputName(id: string): string {
  return `run_${id.replace(/-/g, "_")}`;
}

function generateInputs(scenarios: Scenario[]): string[] {
  const lines: string[] = [
    "  workflow_dispatch:",
    "    inputs:",
    "      strict_validation:",
    "        description: \"Fail jobs on assertion mismatch\"",
    "        type: boolean",
    "        default: true",
  ];

  for (const scenario of scenarios) {
    const inputName = scenarioInputName(scenario.id);
    lines.push(`      ${inputName}:`);
    lines.push(`        description: "Run scenario: ${yamlEscape(scenario.name)}"`);
    lines.push("        type: boolean");
    lines.push("        default: true");
  }

  return lines;
}

function generateMatrixIncludeLines(scenarios: Scenario[]): string[] {
  const lines: string[] = ["      matrix:", "        include:"];

  for (const scenario of scenarios) {
    const hasExpected = Object.keys(scenario.expected).length > 0;

    lines.push(`          - id: ${scenario.id}`);
    lines.push(`            name: "${yamlEscape(scenario.name)}"`);
    lines.push(`            has_expected: ${hasExpected}`);
  }

  return lines;
}

// ---------------------------------------------------------------------------
// Workflow YAML generation
// ---------------------------------------------------------------------------

function generateWorkflow(): string {
  const lines: string[] = [];

  lines.push("# AUTO-GENERATED by scripts/generate-self-test.ts — do not edit manually");
  lines.push("# Regenerate: npx tsx scripts/generate-self-test.ts");
  lines.push("");
  lines.push("name: Self-Test");
  lines.push("");
  lines.push("on:");
  lines.push(...generateInputs(SELF_TEST_SCENARIOS));
  lines.push("");
  lines.push("concurrency:");
  lines.push("  group: self-test");
  lines.push("  cancel-in-progress: true");
  lines.push("");
  lines.push("jobs:");
  lines.push("  scenario:");
  lines.push("    name: Scenario — ${{ matrix.name }}");
  lines.push("    runs-on: ubuntu-latest");
  lines.push("    strategy:");
  lines.push("      max-parallel: 1");
  lines.push("      fail-fast: false");
  lines.push(...generateMatrixIncludeLines(SELF_TEST_SCENARIOS));
  lines.push("    steps:");
  lines.push("      - uses: actions/checkout@v4");
  lines.push("");
  lines.push("      - name: Check scenario enabled");
  lines.push("        id: gate");
  lines.push("        env:");
  lines.push("          SCENARIO_ID: ${{ matrix.id }}");
  lines.push("        run: node scripts/check-scenario-enabled.mjs");
  lines.push("");
  lines.push("      - name: Start monitor");
  lines.push("        id: monitor");
  lines.push("        if: ${{ steps.gate.outputs.enabled == 'true' }}");
  lines.push("        uses: hesreallyhim/github-api-usage-monitor@main");
  lines.push("        with:");
  lines.push("          token: ${{ secrets.GITHUB_TOKEN }}");
  lines.push("          diagnostics: true");
  lines.push(`          artifact_name: ${ARTIFACT_PREFIX}-\${{ matrix.id }}`);
  lines.push("");
  lines.push("      - name: Run scenario");
  lines.push("        if: ${{ steps.gate.outputs.enabled == 'true' }}");
  lines.push("        env:");
  lines.push("          TOKEN: ${{ secrets.GITHUB_TOKEN }}");
  lines.push("          REPO: ${{ github.repository }}");
  lines.push("          SCENARIO_ID: ${{ matrix.id }}");
  lines.push("        run: node scripts/run-scenario.mjs");
  lines.push("");
  lines.push("  scenario-diag:");
  lines.push("    name: Diagnostics — ${{ matrix.name }}");
  lines.push("    runs-on: ubuntu-latest");
  lines.push("    needs: [scenario]");
  lines.push("    strategy:");
  lines.push("      max-parallel: 1");
  lines.push("      fail-fast: false");
  lines.push(...generateMatrixIncludeLines(SELF_TEST_SCENARIOS));
  lines.push("    steps:");
  lines.push("      - uses: actions/checkout@v4");
  lines.push("");
  lines.push("      - name: Check scenario enabled");
  lines.push("        id: gate");
  lines.push("        env:");
  lines.push("          SCENARIO_ID: ${{ matrix.id }}");
  lines.push("        run: node scripts/check-scenario-enabled.mjs");
  lines.push("");
  lines.push("      - name: Download diagnostics artifacts");
  lines.push(
    "        if: ${{ steps.gate.outputs.enabled == 'true' && needs.scenario.result != 'skipped' }}"
  );
  lines.push("        uses: actions/download-artifact@v6");
  lines.push("        with:");
  lines.push(`          name: ${ARTIFACT_PREFIX}-\${{ matrix.id }}`);
  lines.push("          path: ${{ runner.temp }}/github-api-usage-monitor-artifacts/${{ matrix.id }}");
  lines.push("");
  lines.push("      - name: Validate expectations");
  lines.push(
    "        if: ${{ steps.gate.outputs.enabled == 'true' && matrix.has_expected && needs.scenario.result == 'success' }}"
  );
  lines.push("        env:");
  lines.push("          STATE_DIR: ${{ runner.temp }}/github-api-usage-monitor-artifacts/${{ matrix.id }}");
  lines.push("          STRICT_VALIDATION: ${{ inputs.strict_validation }}");
  lines.push("          SCENARIO_ID: ${{ matrix.id }}");
  lines.push("        run: node scripts/validate-scenario.mjs");
  lines.push("");
  lines.push("      - name: Render diagnostics");
  lines.push(
    "        if: ${{ steps.gate.outputs.enabled == 'true' && needs.scenario.result != 'skipped' }}"
  );
  lines.push("        env:");
  lines.push("          STATE_DIR: ${{ runner.temp }}/github-api-usage-monitor-artifacts/${{ matrix.id }}");
  lines.push("          SCENARIO_NAME: ${{ matrix.name }}");
  lines.push("        run: node scripts/render-diagnostics.mjs >> \"$GITHUB_STEP_SUMMARY\"");

  return lines.join("\n") + "\n";
}

function generateRealisticWorkflow(): string | null {
  if (REALISTIC_SCENARIOS.length === 0) {
    return null;
  }

  const lines: string[] = [];

  lines.push("# AUTO-GENERATED by scripts/generate-self-test.ts — do not edit manually");
  lines.push("# Regenerate: npx tsx scripts/generate-self-test.ts");
  lines.push("");
  lines.push("name: Realistic Test");
  lines.push("");
  lines.push("on:");
  lines.push("  workflow_dispatch:");
  lines.push("");
  lines.push("concurrency:");
  lines.push("  group: realistic-test");
  lines.push("  cancel-in-progress: true");
  lines.push("");
  lines.push("jobs:");
  lines.push("  realistic:");
  lines.push("    name: Realistic — ${{ matrix.name }}");
  lines.push("    runs-on: ubuntu-latest");
  lines.push("    strategy:");
  lines.push("      max-parallel: 1");
  lines.push("      fail-fast: false");
  lines.push(...generateMatrixIncludeLines(REALISTIC_SCENARIOS));
  lines.push("    steps:");
  lines.push("      - uses: actions/checkout@v4");
  lines.push("");
  lines.push("      - name: Start monitor");
  lines.push("        id: monitor");
  lines.push("        uses: hesreallyhim/github-api-usage-monitor@main");
  lines.push("        with:");
  lines.push("          token: ${{ secrets.GITHUB_TOKEN }}");
  lines.push("          diagnostics: true");
  lines.push(`          artifact_name: ${ARTIFACT_PREFIX}-\${{ matrix.id }}`);
  lines.push("");
  lines.push("      - name: Run scenario");
  lines.push("        env:");
  lines.push("          TOKEN: ${{ secrets.GITHUB_TOKEN }}");
  lines.push("          REPO: ${{ github.repository }}");
  lines.push("          SCENARIO_ID: ${{ matrix.id }}");
  lines.push("        run: node scripts/run-scenario.mjs");
  lines.push("");
  lines.push("  realistic-diag:");
  lines.push("    name: Diagnostics — ${{ matrix.name }}");
  lines.push("    runs-on: ubuntu-latest");
  lines.push("    needs: [realistic]");
  lines.push("    if: ${{ needs.realistic.result != 'skipped' }}");
  lines.push("    strategy:");
  lines.push("      max-parallel: 1");
  lines.push("      fail-fast: false");
  lines.push(...generateMatrixIncludeLines(REALISTIC_SCENARIOS));
  lines.push("    steps:");
  lines.push("      - uses: actions/checkout@v4");
  lines.push("");
  lines.push("      - name: Download diagnostics artifacts");
  lines.push("        uses: actions/download-artifact@v6");
  lines.push("        with:");
  lines.push(`          name: ${ARTIFACT_PREFIX}-\${{ matrix.id }}`);
  lines.push("          path: ${{ runner.temp }}/github-api-usage-monitor-artifacts/${{ matrix.id }}");
  lines.push("");
  lines.push("      - name: Render diagnostics");
  lines.push("        env:");
  lines.push("          STATE_DIR: ${{ runner.temp }}/github-api-usage-monitor-artifacts/${{ matrix.id }}");
  lines.push("          SCENARIO_NAME: ${{ matrix.name }}");
  lines.push("        run: node scripts/render-diagnostics.mjs >> \"$GITHUB_STEP_SUMMARY\"");

  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// Manifest generation
// ---------------------------------------------------------------------------

function generateManifest(scenarios: Scenario[]): void {
  const payload = { scenarios };
  writeFileSync(manifestPath, JSON.stringify(payload, null, 2) + "\n", "utf-8");
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  const yaml = generateWorkflow();
  const realisticYaml = generateRealisticWorkflow();

  // Ensure output directory exists
  const workflowDir = dirname(workflowPath);
  mkdirSync(workflowDir, { recursive: true });

  writeFileSync(workflowPath, yaml, "utf-8");
  if (realisticYaml) {
    writeFileSync(realisticWorkflowPath, realisticYaml, "utf-8");
  }
  generateManifest(SCENARIOS);

  console.log(`Generated: ${workflowPath}`);
  if (realisticYaml) {
    console.log(`Generated: ${realisticWorkflowPath}`);
  }
  console.log(`Generated: ${manifestPath}`);
  console.log(`Scenarios: ${SCENARIOS.length}`);
  console.log(`Jobs: ${realisticYaml ? 4 : 2} (matrixed scenarios + diagnostics)`);
}

main();
